origin $00097626

credits("CHIEF PROGRAMMER    ")
credits("PROGRAM COORDINATOR            ")
credits("                       YAMA1")
credits(" ASSISTANT PROGRAMMER1    ")
credits("                      ")
credits("                           MIZORAN")
credits("CHIEF DESIGNER  ")
credits("    GRAPHIC COORDINATOR    ")
credits("                             TARO.S")
    dw $45D1
credits(" DESIGNER   ")
credits("                         ")
credits("                          SAYSHI     MT.MAYA")
credits("SOUND PROGRAMMER        ")
credits("                         ")
credits("                        XOR   ")
credits(" TOTAL COORDINATOR        ")
credits("                           ")
credits("                  PAL-KO")
    dw $45CB  
credits("   SPECIAL THANKS TO                    ")
credits("                            MOMONGA MOMO")
credits("                                                            ")
credits("   LITTLE SUN")
credits("   LARIE")
credits("                                                             ")
credits("  THUNDER")
credits("                                                                      ")
credits("  CAPCOM ARCADE STAFF")
credits("                                                           ")
credits("  PANPAKAPANN")
credits("   FILLY")
credits("                                                             ")
credits("  THE HI MASTER") 
credits("                                                                                    ")
origin $00097E47  
    db $09
